# Generated by Django 5.2.1 on 2025-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('start', 'start'), ('finish', 'finish')], default='waiting', max_length=10),
        ),
    ]
