# Generated by Django 5.2.1 on 2025-05-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
